### PR TITLE
fixed RESIZE-FILE

### LINKED ISSUE #189: RESIZE-FILE test fails on MSYS2/Cygwin
RESIZE-FILE tests in t_file.fth fail with these messages:

```
cd ../../fth && ../platforms/unix/pforth_standalone -q t_file.fth
Include t_tools.fth
    include added 1712 bytes,38292 left.
(got=87, expected=37) INCORRECT RESULT: T{ FID2 @ FILE-SIZE -> 37. 0 }T
(got=87, expected=37) INCORRECT RESULT: T{ CBUF BUF 100 FID2 @ READ-FILE -> 37 0 }T
(got=-1, expected=0) INCORRECT RESULT: T{ PAD 38 BUF 38 S= -> FALSE }T
...
  91 passed,    3 failed.
make: *** [Makefile:172: test] Error 40
```

Tested on Cygwin (x86_64) and MSYS2 (Cygwin based)

### PR DESCRIPTION
**Pull request by guberathome**
This fixes #189 .

Since we were already through the looking glass anyway (by putting NetBSD specific code into /csrc/stdio/pf_fileio_stdio.c) 
and Cygwin stil did not work, the cleaner solution was to implement TruncateFile via Unix-API.

This was tested (make clean test) on Cygwin/MSYS2, FreeBSD, NetBSD, Linux/Manjaro.

### CODE REVIEW

File: csrc/stdio/pf_fileio_stdio.c [hunk 1]
```diff
@@ -64,39 +66,34 @@ static bool_t CopyFile( FileStream *From, FileStream *To, long Size)
...
 */
 
-#include<fcntl.h>
-
-/* note: we do not malloc this, so we need not to free it after use! */
-static char getFilePathFromStreamData[PATH_MAX];
-
-static char* getFilePathFromStream( FileStream* File)
+/* Copy SIZE bytes from File FROM to File TO.  Return non-FALSE on error. */
+static bool_t CopyFile( FileStream *From, FileStream *To, long Size)
```
Comment (philburk) [inline csrc/stdio/pf_fileio_stdio.c:74]: Note that CopyFile did not get changed. it just moved.

**Review by philburk — APPROVED** [review]
Thanks. This is a bit tricky but it seems right.
